starting fpl tests
kushalkolar/fastplotlib pull request #153
Opened 2023-03-24 20:25 UTC by clewis7

should be able to starting creating ground truths 

works on #152

2023-03-29 14:26 UTC, clewis7 commented
current updates: 

creating ground truth for simple and comparison seems to be working 

commented out some of the stuff that pygfx uses (can try to integrate back in but not sure if it is relevant for us),  can do zenodo upload eventually for ground truth files like for mesmerize

going to continue adding examples

2023-03-30 01:09 UTC, kushalkolar commented on examples/features/2Dcmap.py
> +image_graphic.cmap = "viridis"
test a few more cmaps, "jet", "gray", "turbo"

2023-03-30 01:15 UTC, kushalkolar requested changes

2023-03-30 01:15 UTC, kushalkolar commented on examples/features/2Dcmap.py
don't start names with a number and use all lower case

2023-03-30 01:15 UTC, kushalkolar commented on examples/features/colorslice.py
put line, image, etc. graphic tests in individual dirs

2023-03-30 01:15 UTC, kushalkolar commented on examples/validation/2Drgb.py
organize the tests by graphic type

2023-03-30 01:15 UTC, kushalkolar commented on notebooks/gridplot.ipynb
remove these from here

2023-03-30 01:17 UTC, kushalkolar commented on examples/features/2Drgbvminvmax.py
> +img = np.asarray(plot.renderer.target.draw())
take images before and after changing things

2023-03-30 01:17 UTC, kushalkolar commented on examples/features/colorslice.py
> +img = np.asarray(plot.renderer.target.draw())
take images before and after changing things

2023-03-30 01:17 UTC, kushalkolar commented
a good start but you'll have to start a new branch and move over all the tests without the large binary files

2023-03-31 13:33 UTC, closed without merging