finish buttons for toolbar
kushalkolar/fastplotlib pull request #207
Opened 2023-05-24 12:57 UTC by clewis7

finishes #149 

added record button, need to make image widget toolbar

2023-05-25 00:19 UTC, kushalkolar requested changes

2023-05-25 00:19 UTC, kushalkolar commented on fastplotlib/layouts/_gridplot.py
> +                self.plot.record_start(f"./{datetime.now().isoformat()}.mp4")
ISO format returns colons and periods, so replace those with underscores. I think windows will complain with those characters. I think you can just do `.replace()` on a str

2023-05-25 00:19 UTC, kushalkolar commented on fastplotlib/layouts/_gridplot.py
> +            except ModuleNotFoundError or FileExistsError:
just allow broad `Exception` if a weirder issue occurs

2023-05-25 00:19 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +class ImageWidgetToolbar:
most of the stuff in here is not necessary, you can just get the toolbar from the `Plot` or `GridPlot` instance.

2023-05-25 00:19 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +    def link_play(self):
I don't this this method is necessary, just call `jlink` in __init__?

2023-05-25 00:19 UTC, kushalkolar commented
what about this for flip: https://fontawesome.com/icons/arrows-up-down?f=sharp&s=light

2023-05-25 13:21 UTC, clewis7 commented
got rid of redundant code, `iw.show()` method might need some work but everything is functional

2023-06-02 19:33 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +            # self.plot.canvas,
```suggestion
```

2023-06-02 19:58 UTC, kushalkolar approved these changes

2023-06-02 19:58 UTC, merged