set_data()
kushalkolar/fastplotlib pull request #216
Opened 2023-06-07 18:37 UTC by clewis7

#190 

add public method to ImageWidget to change the data

2023-06-08 04:53 UTC, kushalkolar requested changes

2023-06-08 04:53 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +        if reset_current_index:
change to `reset_indices`, which resets indices for all dimensions

2023-06-08 04:53 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +            positions = list(product(range(self.plot.shape[0]), range(self.plot.shape[1])))
this is unecessary, `GridPlot` is iterable :smile:

2023-06-08 04:53 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +            for i, (new_darray, darray) in enumerate(zip(new_data, self._data)):
just add the image widget's gridplot instance to the `zip`

2023-06-08 04:53 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +            positions = list(product(range(self.plot.shape[0]), range(self.plot.shape[1])))
```python
for subplot in gridplot:
  subplot#
```

2023-06-08 04:53 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +                self.plot[positions[i][0], positions[i][1]].graphics[0].data = self._data[i][self.current_index["t"]]
add a comment that we assume `graphics[0]` is always the "image widget manged data"

2023-06-08 04:53 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +        if reset_vmin_vmax and len(self.vmin_vmax_sliders) != 0:
this should happen regardless of vmin vmax sliders existing, only based on the kwarg `reset_vmin_vmax`

2023-06-08 10:27 UTC, clewis7 commented
running into a small issue for setting the data when the ndims of the data increase beyond "txy"

setting the overall data:
`self._data[0] = new_data`

however, if the dims are higher than 3 and I am trying to update the current displayed image, I get broadcasting errors because the shapes become mismatched
`self.plot.graphics[0].data = self._data[0][self.current_index["t"]]`

would need to do something like 
`self.plot.graphics[0].data = self._data[0][self.current_index["t"]]self.current_index["z"]` etc.
for whatever dims you are capable of sliding through, but I'm not sure how to make this work if you have an indeterminate amount of dims you could be sliding through

2023-06-08 12:36 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +        if reset_vmin_vmax and len(self.vmin_vmax_sliders) != 0:
Modify reset_vmin_vmax() so that it works when no sliders are available.

2023-06-08 12:44 UTC, kushalkolar commented
Just do the 0th index for all dims upto the last 2. 

Also I just realized we shouldn't directly set the graphic data, if windows functions or something are being used etc. So I would just set the current_index property. But it doesn't do anything if the current index is the same! So you could make a private method that has the logic for the current index setter with a "force" argument to force the update.

2023-06-09 13:54 UTC, clewis7 commented
the examples I have to set_data are working locally, I think it is sufficient to just force a call to the current index setter in order to get the graphics to update

2023-06-09 14:04 UTC, kushalkolar commented
Maybe it's true that a simple call to the current_index setter is sufficient to set the image graphic data, haven't seen that code in a while. If it works then it works! :D

2023-06-09 14:04 UTC, kushalkolar commented
Maybe it's true that a simple call to the current_index setter is sufficient to set the image graphic data, haven't seen that code in a while. If it works then it works! :D

2023-06-10 09:18 UTC, kushalkolar approved these changes

2023-06-10 09:18 UTC, merged