add insert_graphic method
kushalkolar/fastplotlib pull request #225
Opened 2023-06-12 20:18 UTC by clewis7

method allows the insertion of a graphic at a given `position` and `z_level` in `self.graphics`

will help me solve my `ImageWidget` of changing shapes in `set_data()`

2023-06-12 23:28 UTC, kushalkolar requested changes

2023-06-12 23:28 UTC, kushalkolar commented on fastplotlib/layouts/_base.py
> +            self._graphics.insert(position, loc)  # add hex id string for referencing this graphic instance
Can you move this logic from here and `add_graphic()` to a private method that is used for both `insert_graphic()` and `add_graphic()`, else it gets difficult to maintain with essential the same code in two locations.

2023-06-13 12:29 UTC, clewis7 commented
not sure if this is what you meant, but it reduces the redundancy

2023-06-15 20:25 UTC, kushalkolar requested changes

2023-06-15 20:25 UTC, kushalkolar commented on fastplotlib/layouts/_base.py
> +        Replaces graphic at current index if it exists.
> Replaces graphic at current index if it exists.

?

2023-06-15 20:25 UTC, kushalkolar commented on fastplotlib/layouts/_base.py
> +            will place at last possible position.
This doesn't seem right, shouldn't it be if the passed `index` > len(graphics), then it just appends to the end instead of insert?

2023-06-15 20:25 UTC, kushalkolar commented on fastplotlib/layouts/_base.py
> +            Note: this must be a real Graphic instance and not a proxy
```suggestion
Note: must be a real Graphic instance, not a weakref proxy to a Graphic
```

2023-06-15 20:25 UTC, kushalkolar commented on fastplotlib/layouts/_base.py
> +            z-level to place graphic. Will default place the graphic at the 'index' argument.
```suggestion
z axis position to place Graphic. If ``None``, uses value of `index` argument
```

2023-06-15 20:49 UTC, clewis7 commented on fastplotlib/layouts/_base.py
> +        Replaces graphic at current index if it exists.
```suggestion

```

2023-06-15 20:49 UTC, clewis7 commented on fastplotlib/layouts/_base.py
> +        Insert graphic into scene at given position (index) in stored graphics.
```suggestion
        Insert graphic into scene at given position ``index`` in stored graphics.
```

2023-06-15 20:49 UTC, clewis7 commented on fastplotlib/layouts/_base.py
> +            will place at last possible position.
```suggestion
            Index to insert graphic. 
```

2023-06-15 20:49 UTC, clewis7 commented on fastplotlib/layouts/_base.py
> +        if index >= len(self._graphics):
```suggestion
        if index > len(self._graphics):
```

2023-06-15 21:25 UTC, kushalkolar commented
tests failing, I guess something weird with storing the pointer of a `LineCollection`? Because that example adds a `LinearSelector` to a `Line` first, but it's failing later when it gets to adding a `LinearSelector` to a `LineCollection`: https://github.com/kushalkolar/fastplotlib/actions/runs/5283472036/jobs/9559793064?pr=225#step:9:100

2023-06-16 17:57 UTC, kushalkolar approved these changes

2023-06-16 17:57 UTC, merged